# site settings
title: Jeremiah Bonney
subtitle: My WIP site
email: fakemail@donotemail.com
description: A responsive site template designed by HTML5 Up<br /> and released under the Creative Commons.
baseurl: "" # the subpath of your site, e.g. /blog
url: https://jbonney.dev
author: Jeremiah Bonney
street_address: 1234 Somewhere Road
city: Nashville
state: TN
zip_code: 55555
country: United States of America
phone: (716) 555-5555

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url: https://github.com/jeremiahbonney
gitlab_url: https://gitlab.com/u/jbonney
googleplus_url:
instagram_url:
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: https://twitter.com/bonneyandclyde

# build settings
markdown: kramdown

sass:
  style: compressed
